### ISSUE TITLE
Projects: add csv/excel export

### ISSUE THREAD

**Issue by ybakos** [OregonStateUniversity/ltpbr-explorer#337]

**Comment by joewheaton** [comment]
This is cool. We should discuss with Philip and @nick4rivers whether or not a geopackage export or even showing you how to use our pip module for making riverscapes projects out of these projects is worthwhile at the same time. This would mean a user can download a CSV/Excel file they know what to do with, but if they download a Riverscape Project, it can be viewed in our QGIS and ArcGIS viewers as well as uploaded to the Data Exchange.

**Comment by ybakos** [comment]
Only add the action format - no link. Per NW 11/10/23.
