### ISSUE TITLE
Feedback on shape of JSON returned/exchanged for API

### ISSUE THREAD

**Issue by joewheaton** [OregonStateUniversity/ltpbr-explorer#364]
From your 10/20/23 email @ybakos:
> I have shaped a sample API for organizations, to start. Example:
> 
> List of organizations:
> https://bda-explorer.herokuapp.com/organizations.json
> 
> Single organization:
> https://bda-explorer.herokuapp.com/organizations/1.json

For @mattreimer a single organization is looking like:
``` json
{
  "id": 1,
  "name": "NOAA Fisheries",
  "description": "The National Marine Fisheries Service (NMFS), informally known as NOAA Fisheries, is a United States federal agency within the U.S. Department of Commerce's National Oceanic and Atmospheric Administration (NOAA) that is responsible for the stewardship of U.S. national marine resources.",
  "contact": "1-888-990-6622",
  "website": "https://www.fisheries.noaa.gov/",
  "created_at": "2022-02-18T19:04:16.669Z",
  "updated_at": "2023-10-22T16:40:11.596Z",
  "url": "https://bda-explorer.herokuapp.com/organizations/1.json"
}
```
@mattreimer, just to get the dialog going, we should discuss if any of these are ones we should add. I think for now, the simplest thing might be for us to both have an additional field referring to the other's url (e.g. for us, we would add an optional `"LTPBR_Explorer_URL": "https://bda-explorer.herokuapp.com/organizations/1.json"`, and for @ybakos he might add a `"RC_Org_URL":"https://data.riverscapes.net/o/fe204da2-8c52-4165-9e90-f4c9807ac57a/overview"`. 

@ybakos, in the Data Exchange, we do have organizations, they are a little different, but some obvious overlap. Here I don't imagine us syncing each others organizations, but it would be nice to have a dedicated hyperlink from yours to "Riverscapes Data Exchange Organization Page", and vice versa for us to have a link to "LTPBR Explorer Organization Page", if the field is populated.  As you can see in the [NOAA org page](https://data.riverscapes.net/o/fe204da2-8c52-4165-9e90-f4c9807ac57a/overview), we also have the equivalent of your  `"name"`, and `"description"` and a logo, but we also have an overview, we keep track of [their projects](https://data.riverscapes.net/o/fe204da2-8c52-4165-9e90-f4c9807ac57a/projects) in the data exchange (here is [one](https://data.riverscapes.net/o/d4c09f98-13de-492a-8f55-31f6477a1083/projects) with actual projects), and their collections. It is pretty simple. We don't have an organization website field, and just let them add that in their overview description.

**Comment by MattReimer** [comment]
In the exchange Organizations, like all our objects can have metadata for fields like this so I don't need to change any code to accomplish this if we're looking to create a relationship between orgs behind the scenes

**Comment by ybakos** [comment]
See #372
