### ISSUE TITLE
/states: Sort by project count

### ISSUE THREAD

**Issue by joewheaton** [OregonStateUniversity/ltpbr-explorer#365]
I really liked what you did @ybakos  on the sort order on [Organizations](https://bda-explorer.herokuapp.com/organizations):

> Most visible is a change to the Organizations list. They were previously unordered and arbitrary, and now that list is ordered by number of project affiliations, and then name.
>![image](https://github.com/OregonStateUniversity/ltpbr-explorer/assets/9723905/a95ebe73-3899-41d8-aa9f-f0779667d148)

I would love to see for [States](https://bda-explorer.herokuapp.com/states) either:
- the same logic to sort by Project Count 
- or option to choose how to sort the list (e.g. by alphabetical, project count, total structures or total length

BTW, I love the state summary pages. Really nice.

**Comment by ybakos** [comment]
Agreed, sounds good!
