### ISSUE TITLE
Revise styles & branding to match Riverscapes aesthetic & design guide

### ISSUE THREAD

**Issue by ybakos** [OregonStateUniversity/ltpbr-explorer#367]
Initial overhaul of the app look & feel.
See basecamp for assets and guides.

**Comment by ybakos** [comment]
![Screenshot 2023-11-14 at 9 55 48 AM](https://github.com/OregonStateUniversity/ltpbr-explorer/assets/5502/490323f6-7faf-449c-8ffe-1e99afedeb69)

@nick4rivers @joewheaton Only a draft work in progress, far from done, but giving you a sense of where this is headed. I'm going to check in with Philip regarding the details.

**Comment by joewheaton** [comment]
See reply in email. Happy to move conversation here if you prefer.

**Comment by ybakos** [comment]
![Screenshot 2023-12-01 at 3 29 34 PM](https://github.com/OregonStateUniversity/ltpbr-explorer/assets/5502/eb787eae-d7ad-4a4a-904d-1cd9d58c12f4)

**Comment by ybakos** [comment]
Riverscape-themed app icon added to navbar.

![Screenshot 2024-02-16 at 4 15 03 PM](https://github.com/OregonStateUniversity/ltpbr-explorer/assets/5502/21442841-dc08-46df-afd9-d88bcd441acc)

**Comment by ybakos** [comment]
Updated favicons.

**Comment by ybakos** [comment]
Closing this large-scope issue, as the general style overhaul is complete. Will address additional style changes in future, atomic issues.
